// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJzz81CkfZk84L3zRHAL9kMYufzbvj8w',
    appId: '1:904670447535:web:bc10bf070054099cadd15a',
    messagingSenderId: '904670447535',
    projectId: 'tubes-iot-affe1',
    authDomain: 'tubes-iot-affe1.firebaseapp.com',
    databaseURL: 'https://tubes-iot-affe1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-iot-affe1.appspot.com',
    measurementId: 'G-SGEFF01CWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSFYDuZ2Q7WYgCbSxDbwUiH8WbFOlrgM',
    appId: '1:904670447535:android:7d3187f0ebeee470add15a',
    messagingSenderId: '904670447535',
    projectId: 'tubes-iot-affe1',
    databaseURL: 'https://tubes-iot-affe1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-iot-affe1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Xsgo4eJPA8fyFAucwOQj0OP1ensB6H8',
    appId: '1:904670447535:ios:8fe17cfa7bddb299add15a',
    messagingSenderId: '904670447535',
    projectId: 'tubes-iot-affe1',
    databaseURL: 'https://tubes-iot-affe1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-iot-affe1.appspot.com',
    iosBundleId: 'com.example.tubesIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Xsgo4eJPA8fyFAucwOQj0OP1ensB6H8',
    appId: '1:904670447535:ios:0edece8bf08a26c0add15a',
    messagingSenderId: '904670447535',
    projectId: 'tubes-iot-affe1',
    databaseURL: 'https://tubes-iot-affe1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-iot-affe1.appspot.com',
    iosBundleId: 'com.example.tubesIot.RunnerTests',
  );
}
